### PR TITLE
Update code to pass CI and Censys Module

### PR DESCRIPTION
**Pull request by thehappydinoa**
- Updated CI
- Updated README.md
- Updated Censys discovery module
- Simplified `MissingKey` class

### CODE REVIEW

**Comment by thehappydinoa** [comment]
Hey, @L1ghtn1ng I can't seem to get ShiftLeft to pass. Do you have any ideas of how to fix this?

**Comment by L1ghtn1ng** [comment]
Don't worry about shiftleft if everything else passes then all good. Can you please iterate through the pages as we are missing data due to only having one page

**Comment by thehappydinoa** [comment]
@L1ghtn1ng Yeah I would be happy to do that

**Comment by thehappydinoa** [comment]
Hey the issue was that you had actually set it to only gather 1 page. I removed the page kwarg and now it should get all of them. After those tests pass would you mind merging it in? I am all done on my side, thanks!

**Comment by L1ghtn1ng** [comment]
@thehappydinoa The change you did to the missing key class, if I recall correctly that will break showing the key

**Comment by thehappydinoa** [comment]
> @thehappydinoa The change you did to the missing key class, if I recall correctly that will break showing the key is missing

@L1ghtn1ng I did, but I believe I did it in a way that worked for all use cases. If you were able to give me a use case where it doesn't work I could totally fix that for you. Thanks!

**Comment by L1ghtn1ng** [comment]
Thanks for this

**Comment by L1ghtn1ng** [comment]
turns out the way you did the missing key class is perfect

**Pull request merged**
